---

- name: Installation de la base de données mysql
  hosts: database
  become: true
  roles:
    - { role: database, tags: ["database"] }

- name: Install applicative server
  hosts: api
  become: true
  roles:
    - { role: runtime, tags: ["runtime"] }
    - { role: app, tags: ["app"] }

- name: Installation de nginx
  hosts: nginx
  become: true
  roles:
    - { role: geerlingguy.nginx, tags: ["nginx"] }
    - { role: webserver, tags: ["webserver"] }

- name: Installation de Certbot (TLS Let's Encrypt)
  hosts: nginx
  become: true
  roles:
    - { role: geerlingguy.certbot, tags: ["certbot"] }
