---

# Rôle pour l'installation et la configuration de Nginx
- src: geerlingguy.nginx
  version: 3.2.0

# Rôle pour l'installation et la configuration de MySQL
- src: geerlingguy.mysql
  version: 4.3.2

# Rôle pour l'installation et la configuration de Certbot (Let's Encrypt)
- src: geerlingguy.certbot
  version: 5.4.1
