---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart maildev
  ansible.builtin.systemd:
    name: maildev
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
